#!/bin/sh

# Removes old events from specified file (default: /home/sebastiano/.local/share/sdep/once).

# Usage: sdep-clear [file]

file="/home/sebastiano/.local/share/sdep/${1:-once}"
temp=$(mktemp)

sdep -t <"$file" >"$temp"
mv "$temp" "$file"
