#!/bin/sh

# Open specified file in sdep folder in editor.

# Usage: sdep-edit [file]
# No options = once

sdepdata="${XDG_DATA_HOME:-$HOME/.local/share}/sdep"

file="$sdepdata/${1:-once}"
editor=${VISUAL:-vi}

$editor "$file"
