#!/bin/sh

# Run this at boot to receive a notification about past events that you might
# have missed (based on sdep-list).

# Requires: a command to send notifications such as herbe or notify-send.

#notify="notify-send -t 3600000"
notify=herbe

sdep-list past | \
while read text; do
	date=$(echo "$text" | sed 's/\t.*//')
	event=$(echo "$text" | sed 's/.*\t//')
	$notify "$date" "$event"
done
